name: Build and Test Spring Petclinic

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run tests with Maven
        run: ./mvnw package 
      
      - name: Archive test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports



